---

- hosts: development
  become: yes
  vars:
    ansible_user: ubuntu
    ansible_become_method: su
    app_user: bevvie
    python_version: python3
  roles:
    - base
    - users
    - mongodb
    - redis
    - web
    - nginx
    - application
    - pm2



